<?php

namespace Tests\Feature;

use App\Models\Example;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;

class ExampleControllerTest extends TestCase
{
    use WithFaker;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->signInAdmin();
    }

    /** @test */
    public function index_route_returns_paginated_list_of_examples()
    {
        $count = 10;

        $examples = Example::factory()->count($count)->create();

        $this->getJson(route('examples.index'))
            ->assertSuccessful()
            ->assertJsonCount($count, 'data')
            ->assertJsonStructure([
                'data' => [
                    [
                        'id',
                        'title',
                        'description',
                    ],
                ],
            ])
            ->assertJsonFragment([
                'id' => $examples[0]->id,
                'title' => $examples[0]->title,
                'description' => $examples[0]->description,
            ]);
    }


}
